### PR TITLE
Refactor: Remove redundant self

### PR DESCRIPTION
**Pull request by typerandom**
Removes the redundant places where `var self = this;` has been used.

This PR is is a part of several refactors with goal to clean up the codebase from redundant code.

### CODE REVIEW

**Comment by rdegges** [comment]
+1

**Comment by robertjd** [comment]
LGTM.  What's the rebase for?

**Comment by rdegges** [comment]
Rebase cleans up git history to make it more compact without extraneous commits.

**Comment by robertjd** [comment]
Yes, I'm just asking why it's needed for this PR?  This looks like a FF merge to me.

**Comment by rdegges** [comment]
There are 21 commits that all do the same thing -- which clutters the history. Typically you'd use rebase on stuff like this, in particular, to simplify history / changes / reverts.

**Comment by robertjd** [comment]
I guess I'm just confused because @typerandom typically rebases before the PR? :) rebasing after making a PR is a no-no in my book

**Comment by typerandom** [comment]
@robertjd Yeah, I just kept it for you to easier review the PR :)

**Comment by robertjd** [comment]
Well, if by rebase you mean squash, it's a better workflow (IMO), to do that before the PR (and it makes it easier to review).  Either way, please just merge these change in some form so that we can have them going forward with other features.

**Comment by typerandom** [comment]
Yeah, exactly. By rebase I mean squash :)

**Pull request merged**
