### PR TITLE
Fix omitted Account.save() error

### LINKED ISSUE #403: When calling Account.save() the error is omitted
When making a `Account.save()` call that results in an error, that error is not forwarded to the provided callback.

#### How to reproduce

1. Use the Stormpath SDK to retrieve an account.
2. Using the retrieved account, use [this gist](https://gist.github.com/typerandom/abd1b58d2cb110f0eb64) to replicate the omitted save error.

##### Actual

The text `Expected error but none was provided!` is written to console.

##### Expected

The text `Got error: Account password minimum length not satisfied.` is written to console.

### PR DESCRIPTION
**Pull request by typerandom**
Fixes so that when Account.save() is called, the error from the underlying data store is forwarded to the original callback.

##### How to verify

1. First, verify that you are able to reproduce the steps in the #403 issue.
2. Checkout and link this branch.
3. Rerun the reproduce steps in #403.
4. Verify that the the text `Got error: Account password minimum length not satisfied.` is written to console.

Fixes #403.

### CODE REVIEW

**Comment by typerandom** [comment]
Coverage has decreased, so will look into adding some unit tests for this.

**Comment by typerandom** [comment]
Added test, so please review again.

**Comment by robertjd** [comment]
Looks great!  Please merge if we're not waiting on anything else, we could make this a 0.17.6 version and release with express-stormpath@3.0.1

**Comment by robertjd** [comment]
EDIT: I mean the 3.0.2 version of express-stormpath

**Comment by typerandom** [comment]
@robertjd Thanks! Will do :)

**Pull request merged**
