### PR TITLE
Updates to support stormpath-express changes for specifying accountStore

### PR DESCRIPTION
**Pull request by tuck182**
Allow options object to be passed to handleIdSiteCallback, verifyApplicationPasswordResetToken to support specifying accountStore in stormpath-express library

### CODE REVIEW

**Comment by tuck182** [comment]
That build failed on one test, but I'm getting the same failure when building `master` and `0.10.2`:

```
[2734] stormpath-sdk-node@Menerva git:(f8db883)$ git co 0.10.2
Previous HEAD position was f8db883... Merge pull request #175 from stormpath/revert-174-oauth
HEAD is now at 0b2e1e1... Version bump.
[2735] stormpath-sdk-node@Menerva git:(0b2e1e1)$ npm test

> stormpath@0.10.2 test /Users/tuck/Dev/workspace-ookla/stormpath-sdk-node
> grunt

Running "jshint:gruntfile" (jshint) task

✔ No problems


Running "jshint:lib" (jshint) task

✔ No problems


Running "jshint:test" (jshint) task

✔ No problems


Running "mocha_istanbul:coverage" (mocha_istanbul) task

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  139 passing (575ms)
  1 failing

  1) Client with an app href that has a valid default account store with email verification enabled "before all" hook:
     Uncaught HTTP 401, Stormpath 401 (http://www.stormpath.com/docs/quickstart/connect): Authentication with a valid API Key is required.




=============================================================================
Writing coverage object [/Users/tuck/Dev/workspace-ookla/stormpath-sdk-node/coverage/coverage.json]
Writing coverage reports at [/Users/tuck/Dev/workspace-ookla/stormpath-sdk-node/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 46.05% ( 932/2024 )
Branches     : 26.65% ( 238/893 )
Functions    : 34.11% ( 132/387 )
Lines        : 46.18% ( 931/2016 )
================================================================================
>>
Warning: Task "mocha_istanbul:coverage" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-08-13 20:31:31 UTC)
loading tasks            384ms  ▇▇▇▇▇▇▇▇ 9%
jshint:lib               450ms  ▇▇▇▇▇▇▇▇▇ 11%
jshint:test              974ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 23%
mocha_istanbul:coverage   2.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 56%
Total 4.2s
npm ERR! Test failed.  See above for more details.
```

**Comment by rdegges** [comment]
Hey @tuck182, so -- couple things real quick:

You'll need to remove the modifications you made to `handleIdSiteCallback` -- the reason is that this endpoint doesn't accept any options.

The way the ID site callback handling works is that a route is run once a user has authenticated via ID site. Then the user is redirected back to your web app, which calls this method.

This method basically extracts the JWT from IDsite, validates it, then retrieves the user's account. So the options here won't do anything.

**Comment by robertjd** [comment]
Hi @tuck182 , can you elaborate on what you are trying to achieve?  There is no need to supply an account store when verifying a password reset token.  However you can specify an account store when you begin a password reset workflow, via `resendVerificationEmail`.

Regarding the ID Site modification, can you clarify what options it is you need to pass to the account getter?

Thanks!

**Comment by tuck182** [comment]
@robertjd The goal here (and I've been talking to @rdegges about this) is to provide the express-stormpath library a mechanism for specifying an account store in the client configuration that would then be used in all necessary interactions. The high level guidance Randall gave me was "look for places in the express library that do `req.app.get('stormpathApplication')` as a good starting point for what needs to be updated" so I did that with an expectation that because I don't have a deep knowledge of the underlying API's, I might have a couple misses.

It sounds like two places that *don't* need to have the accountStore passed are `handleIdSiteCallback` and `verifyPasswordResetToken`, which removes the need to make updates to this project. I can go update my stormpath-express PR to remove those dependencies.

**Comment by rdegges** [comment]
Hey @tuck182, I think that sounds right!

Wanna update the PR? Thanks again for all your help with this ^^

**Comment by tuck182** [comment]
I updated https://github.com/stormpath/stormpath-express/pull/79, and I'm closing this one.

**Pull request closed without merging**
